# PostgreSQL Configuration for FS Reconciliation Agents

# Database connection settings
database:
  host: "database"
  port: 5432
  name: "reconciliation_db"
  user: "reconciliation_user"
  password: "reconciliation_password"
  url: "postgresql://reconciliation_user:reconciliation_password@database:5432/reconciliation_db"

# Connection pool settings
pool:
  min_size: 5
  max_size: 20
  max_queries: 50000
  max_inactive_connection_lifetime: 300.0

# Performance settings
performance:
  statement_timeout: 30000
  idle_in_transaction_session_timeout: 300000
  lock_timeout: 10000

# Logging settings
logging:
  log_statement: "none"
  log_min_duration_statement: 1000
  log_checkpoints: false
  log_connections: false
  log_disconnections: false

# Maintenance settings
maintenance:
  autovacuum: true
  autovacuum_vacuum_threshold: 50
  autovacuum_analyze_threshold: 50
  autovacuum_vacuum_scale_factor: 0.2
  autovacuum_analyze_scale_factor: 0.1

# Backup settings
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  compression: true
